### PR TITLE
feat: improve user-supplied authentication param requirements

### PR DESCRIPTION
**Pull request by kunalrgarg**
Since username is not a required parameter for `#connectToPubSubApi`. To properly reflect the needed requirements, this PR adds a new type called `ConnectionDetails` where the username is removed and the organizationId is optional--it will be attempted to be parsed from the accessToken when not provided.

### CODE REVIEW

**Comment by kunalrgarg** [comment]
@pozil I didn't see any Contribution Guidelines for this repo, please let me know if there's anything I can fix! Thanks!

**Comment by pozil** [comment]
@kunalrgarg thanks for the PR. I agree that we can make these two things optional.

However, instead of adding a new `ConnectionDetails` type that conflicts with `ConnectionMetadata` in one of the two `connectToPubSubApi()` calls, could you change `ConnectionMetadata` and make the two fields optional like so:

```js
/**
 * @typedef {Object} ConnectionMetadata
 * @property {string} accessToken
 * @property {string} instanceUrl
 * @property {string} [organizationId] Optional organization ID. Can be omitted when working with user-supplied authentication.
 * @property {string} [username] Optional username. Omitted when working with user-supplied authentication.
 */
```

**Comment by kunalrgarg** [comment]
@pozil Makes sense! I updated the PR to remove ConnectionDetails and modified the respective call sites to use ConnectionMetadata. Please let me know if there's anything else I can address!

**Comment by pozil** [comment]
Thanks for the quick update @kunalrgarg. Everything looks good. I'll merge your PR and release a new version.
Thanks again for the contribution.

**Pull request merged**
