### PR TITLE
update: subscribe to events sequentially

### PR DESCRIPTION
**Pull request by rimokhy**
Hey @pozil, me again with a larger PR.
I've ran into issues with event emitters not being async, which lead to backpressure issue.

You can reproduce it by loading a topic with hundreds of messages and init subscribtion with `subscribeFromEarliestEvent`, it should fail with 
```
Error: 8 RESOURCE_EXHAUSTED: The service received too many connections and doesn't have the resources to accept new connections. rpcId: 6b6424e6-52d1-4536-91ac-eb2eefb48205
```

Issue : 
- Received events are evaluated in parallel, due to async callback on foreach method [here](https://github.com/pozil/pub-sub-api-node-client/blob/main/src/client.js#L327). This results in additional events being called way too much when confronted to a huge stack of events. Event received/consumed counts are also probably impacted.
- Event emitter consumption is too slow, resulting in requesting more events than i am able to consume

Solution :
- Replaced [async foreach callback](https://github.com/pozil/pub-sub-api-node-client/blob/main/src/client.js#L327) with an async loop which awaits each iteration
- Added onData/Error/Status async methods to be able to slow further down consumption based on actual processing time. This could be further improved by using an inmemory queue to process events in parallel, and wait for the queue to be fully consumed before requesting additional events.

Please note that even if I did efforts to not break exposed APIs, I am fully aware that this PR is a lot of changes. I still have the option to fork on my side, so no pressure. I just wanted to share my feedback with you and offer a solution 😄 

Thanks for reading 🚀

### CODE REVIEW

**Comment by rimokhy** [comment]
It seems it would help this issue aswell https://github.com/pozil/pub-sub-api-node-client/issues/38

**Comment by pozil** [comment]
Thanks for the PR and the detailed explanation @rimokhy.

You're right, I need to address the parallel processing issue as raised in #38. However, your proposal introduces too many changes and it attempts to fix something that was baked in the architecture of the Pub/Sub API (not just this client). One of the objectives of the Pub/Sub API is to introduce a limit to the number of subscribed events to get rid of backpressure issues.

So, instead of modifying the client and the event emitter, you should consider requesting events in a limited batch and request additional events once you're done with the current batch. See [Work with flow control for high volumes of events](https://github.com/pozil/pub-sub-api-node-client?tab=readme-ov-file#work-with-flow-control-for-high-volumes-of-events).

**Comment by rimokhy** [comment]
No problem :) thanks for your feedback

**Comment by pozil** [comment]
Actually, I looked into it a bit more closely and I realize that the EventEmitter is the core of the problem as it introduces asynchronicity in event processing thus causing #38.
I may need to make breaking changes in a new release to step away from events in favor of callbacks.

**Comment by pozil** [comment]
Actually, I looked into it a bit more closely and I realize that the EventEmitter is the core of the problem as it introduces asynchronicity in event processing thus causing #38.
I may need to make breaking changes in a new release to step away from events in favor of callbacks.

**Pull request closed without merging**
